spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/pingit
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
    show-sql: true